apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:2K8zgySGZuwlENXZvIqOqP1SXDaiDmevT7sScwsaubsXaAVfmztvFVOi3hs9HILq3sjw/tyqrb5cKim90qEtOtA=,iv:97mCWd9jnEFTSbbw+26bDz0cSvlW3fbWXbuFBGNv+fM=,tag:acsWy+UboNz+7ORSftECZw==,type:comment]
    #ENC[AES256_GCM,data:BgHT/HbSKKv3e+Z9MMLcmRIp9olKmGQ1W4OCFoEqP87OX/uGx/vi0PgKtIc=,iv:F7kcZc7cGkRn50naDHuwNPiAw2jr9q2pj47YdTejdOU=,tag:nMgknP1XSQQSSDSNJRxzkw==,type:comment]
    VIP: ENC[AES256_GCM,data:JKY5wmxBLLk+ITk5+AD0,iv:aCkKKglJ+Ubx14R1FnmXAYkvak+iSTWaN6fgOX2HzZ4=,tag:Sa9+Wo6wqW1puNbJi4BDhg==,type:str]
    #ENC[AES256_GCM,data:mO7Hl6ITYejfMoxuNLAIh7c9td50jvaQskg=,iv:aHUFiRYIpMs6Fai13J0SQKSZ8kOda2YHuliUIuUJ1uE=,tag:MiG4CngGGMpwI4LyUCOsbQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:qJ5AGNio+4PWWuYFGvvB,iv:72leIBEu8HVQZRY37ZIXfd51Pt7cTAZiG7KleoEU1UA=,tag:MA2LYGJxpvntWMYpLlE6hg==,type:str]
    #ENC[AES256_GCM,data:4ZVH2OpcZTyuvuF6iHmXUmFQ1+iac31dAjYheAwOy00tdQ==,iv:f76q96vXmEJ9argtGn8iqz5eP9oNApgq7sfzCIpyUTY=,tag:B89GgvM92YlxjFwqvoAcYw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:g6juwPoV7u/xoAtCDA==,iv:6jAGSYJxTgRo4h4AOv75U0p3zVc2dimBhnBqX8K6jME=,tag:CG6G0s+UWNLoXXzyEwyE5g==,type:str]
    #ENC[AES256_GCM,data:pGRTZX7NRlhar7KxPzn9/COxcSFlvHhmPnejiXmPIz/UD4M0MyE9pbWwyITI3n4=,iv:qg/bxY8U3kpOJufSWEL8GNlRMobCW09vfjqMOeXl9vA=,tag:6P+gVqd7611Xa2B8abdzSA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:oHjrV0FGp2diMd9U3UUBFf1fgAd14OVtsvN4dw6EnA==,iv:UxUsFrPUZ19nMvwHYID3Q/egSYqk+wNEVgnmFzsNZYA=,tag:/E50qg7RuH3HR8hUnLFdcw==,type:str]
    #ENC[AES256_GCM,data:kZYPFP3UlGAkq9AvKwYO4LNfPBTSXj7jdZfjzG8UeUcxKbO8QIdbfX9lu1VzpUQhIWmGNNNd61wChd5jvEu+N6t/Ob99IdkbI4BO5fSGXpM=,iv:ASalvKaiGyh9+KSXkR/4lkgr1HNY35Jd/bF8VCKaZBk=,tag:jwcDpWSyT2EpKDkWeUelFg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:oACczrf8y+I29HUbvXNc,iv:epqBJgjB7Tfn6/kObFz6t9/3FCkyaN4lacKzh53gAtI=,tag:XROFXVRdhEsaCkdC1pp+JQ==,type:str]
    #ENC[AES256_GCM,data:QKj1wA/N1OraL0lSDjfv6qEZHXyOAa5WIZxtb4/ZaX9WP08TYYLtNR+Dw81pQhLYt1CgboA//6a2xHCu6gfvflzrP2U=,iv:H671SwKh5jqeKHJslEWmErQ8B8y3UPCHo5pSJh3aWpU=,tag:s6sqlVw77CgLzeKUAt/3og==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:LbuLwaDDtZEoRZ3XtyE2,iv:XLI+a6/rRy/YpUk6whLwLC/XkD/2h7IeubN+p/TG4Gg=,tag:vcJaDEou2jWbymS4SAAVmQ==,type:str]
    #ENC[AES256_GCM,data:UZgxARC0cLyTep/M4VPNIo6EKKc4ppOVkJP62QB8RVGDwFk05/l0oRB2lrbuhc4zI7/tk1ltE4c=,iv:rRyj+dKFIFjEhtN1oAnNrr5pjheXE5azuVPTkOZ1k0k=,tag:ZJo0JIng8F10CcEa73lYcA==,type:comment]
    #ENC[AES256_GCM,data:VKZVfzlWowcTzFanOOCdB4Pd22Bn3glsSQ==,iv:wh1KIB8WQWJK2l5F3r8U2/Ih6p10eNVDkygCrdt5e4g=,tag:KKIKqsEPTuOnSPBuVPbg3w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:rSvNPUeQfGwu36PAG11iYtzVJnCc5iWlJbYLRxMXm53K0rR+tKMd,iv:eUKbkb2xNSHExXRQ2F73cLlXjxA/A0pR8EjIsk58kVI=,tag:iscibcF1D196+g53oBCt0A==,type:str]
    #ENC[AES256_GCM,data:8ZbjTOR7FJBPug8HZA==,iv:8be5J9Ki1r7DUXmQFWkhLZYvcXNZ6QU4atnqKi5nK1U=,tag:/P9yHI0hAMhW4kv2ud61ng==,type:comment]
    PODNET: ENC[AES256_GCM,data:ujw8j7DHvkOeKX2DQQ==,iv:vCXiaZ4AUncKstsokhnKHClGdTxVv6dc3xDZSIhWVWA=,tag:N3UkouwXPFm9e/fjKab+YA==,type:str]
    SVCNET: ENC[AES256_GCM,data:BRuNfguSYLvSt6CeYg==,iv:2bv/mZbwjnR2yKYF6WbhOuxtSHdwChpoVwDfytCrKi0=,tag:GW9Mm41t2lT2tFU3R1kL1Q==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:mt1qVFJCn5a3kCNE,iv:+QeEZQ2h2gBobD8XOqd/70ZyxaYMGdtwT+QZXxgcxpg=,tag:XFwXbCMeOBRjCadyoVmNhg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:YkZF1VbaM2SSsPSO3BGF,iv:KKd2uAacCrCznfnp8snmXG1+9415pP2uvJZvxH7JPCY=,tag:hMSeW9sFu3bwCHcUxhl2Og==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:Osu3gX0jmcOT7qiEt1Mk,iv:tp1Cag/94Ow7D3wBQmg5XIHTJCkLujFtBZBoXj1JE0k=,tag:T9r6pKEXf8s3svWYvLY8bQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:Lj2MhP7+yPxZ6hBo56Co,iv:tNk5LpIl5xDuqXxy7sa+OKwintoGg4wgfa/+SEUH/iw=,tag:YJkST/SUPn/Vp0LvHuEqSA==,type:str]
    EMAIL: ENC[AES256_GCM,data:zyBli7B9vzljXImnwdh06EP8EB0=,iv:1x4uvLlEZILwetDvL1nJekkKh/xpT83C9y9m/in1zTU=,tag:KrkhaafUNioT0d3fYTurEQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ebSmEGnFlENyFnkD+HNHm8rmfh7e6NsNn2VfiZTKt8XKOsHv8QyQjw==,iv:66ZfjTr67/Nf3qYlqXODZqiyE0MR2u4Im3x5trZ6HUE=,tag:KFZHaAput1C76xjl12gq1Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:LK6TNQ==,iv:hKdXSaSt/4DiKkrIMCgZPGGvu8xk4XY75wjo5v0NXZ8=,tag:HusSC1dlIWcqpqaYXn/pUA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eqvkcqrmrh8cmml7stsshxk9f5ayfwjt0fhw39x388t3v05uheesp4uqjj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSODE5RVRmTndMZWNUeXBW
            OUJFdmtIaDJMUDJuUzdtT2NJMjVvbTU2UVFBCjBCM3pjU1BINXFOTTVMR1FxSitm
            c0owcXRqRm9qVkV2Mk9LQi9ha2NxL1kKLS0tIEoxVDJlZ0x0NUhoNUlVQTZHT1Uy
            SjFYSlkzcURiSUw4eGorbmhRTjc1WmsKNHsKUY35gKplAj/YAzfBWf2F7cYzK/jh
            Rm+ZoGsMZFUxUljVbcqZy9hCRRwAVWbtlljnepCulZqrASgAh15Byg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T23:39:11Z"
    mac: ENC[AES256_GCM,data:8QidrKGqHZx8KIm6inXZrLHZh7PO0bUL9XfTW5DPlokXoUiIGWp/tHdLrdjMlTVf4i4OJscjQWfeJ8a1hqqhhlLbyCSAWDrWJ301iwgANotIitLqpOKR461ocalMGsSGVXf2CCxyllhIGjMJLkm2VvaJ1LR8DPqZS3KncFx+0no=,iv:cQjiLTwU+1km+BKOucfXk9GSlfxFL79f7AbFzrMsOjw=,tag:RbC4bvdafa6DgxLjJcnSnQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
