apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:inXZuPjAFs17XVRkrjTN7rK77V1tYOjvJ9qapfsJcdiSu0CzBf8R5vn3+pB1W1obFmeffl8qz9Fr3XXAhcupid1Oh0gjKOf60BSU5Bf5d0Ucdx/SqeneAMcwjz1NTOuDmlqCz6qsXtpMZeFIQVSnq2foLrQILYnLNcKQiLnduBX6/9cmAzQjTQ9sUK09j6WE2SMBvi+hgHmMSjLswSwYORGxdyjw0xVXtf1A8SbBu5cI5fN5p0b3Zg5HwHNY9hXg0idTizUONNsaTf1WRtt701jp5XXc08qcAKDcOhb0qiDuIsGLJ+jXmiRM9X9kqd8t++Sj+DemjmAnV/f1mkiWDCxMBdMFuBpNGLsPuEtVgHjvHAkKGiOOZxETcDIKRT3m,iv:n4HddqHF+fcLYVHtNN6bzp4ELfaPT63sDPpCgOMiFQY=,tag:8GUKJ5TuQTrfXFZCHikEkA==,type:str]
    identity.pub: ENC[AES256_GCM,data:q2BOSGrGTnObFY2bqMaMChZbgBiyOqVlnSIB5CckdYybs5aOFwccBlohoRn+D0dROM31EUGpM1krN330qlfl86aW3T0xQk45pQ/lRHBNQS4qikmbVq8VxupbTWv6YIkXe+3rQ8FwGNlLoFSFTNkG7qUT6ktDoqynl1hLZaxLjwTU++MM9EjYBBVso/EL4ZUgQgmE04qIn0GJ37X6KtqAe09eZEsbsw5QcE0GBZ7ek3IOkqyKCOgWNx0+9YenzV7GbiA70CyvCUzZ73bgxg==,iv:++KXkRVfVhTyfUqEttEkorU+YlLPhQt+COho9Mlyn+E=,tag:uQs8M00we9rQSBsx/rRBVA==,type:str]
    known_hosts: ENC[AES256_GCM,data:u088FMWaeV12AuV+ggC02sVka39SJNC1uoqFPAz+mSDt+fF6+eKnz1G3Ni1B+1v5vVvKxwV7DAC2/fvx6FdCZdvS4o0m4npFCsVnNvpjZ2smBjalvvv4BtTYh29FNB6IPS/Ya9BwkIP3I5ELryyi2mNBetDx3K4SvR2ixkPwAJiJBkom0K8qrdrvKUJdvFtmg8YH3nhy+/PKopbA9f0rHB3JkTvir2CLccsw,iv:j7neoRxw3RpbHBBzqBuOJ1wfIIyl27k6Z10J3G4K9Uk=,tag:++QNJdF8ZpdXuyhvqQ8ifA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eqvkcqrmrh8cmml7stsshxk9f5ayfwjt0fhw39x388t3v05uheesp4uqjj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTitUeW9PblZEQStXc3Rl
            eFgxVVprYW5oMzhFRVl4QS9QY281N0dXeUhnCnk3WTNHWEtjYU9OVmUrS3oySXB0
            dmJmRG1Md0RsbmJpeUtOYnVSZm1TVEUKLS0tIEpZWHZCRHJQN2xyUWk4TG0ySlpC
            cTNRNnlxKzFlZGFhOXJwbFEwbkVhVHMKo1DiI7veYBxHHMO8wAO+0qb28TQCP1bx
            BsneLpiGH/0xmk5zjCtySmoeCHpCcAXBDstWv7+28lZAyEi3B2gKsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T22:50:25Z"
    mac: ENC[AES256_GCM,data:OhcmZCCypzlbixmtALS/xDSH4j4sF9mf9gZwdOUCxCj9bVPeMhJ1XoclC+FCQ3ML5CM9QJnByCrEcAhO1ZB8VNc4byQ0Zuiw6gcAB6KArkFXOy1NLM8mza8YtvLd0dDv1vR0QhoJt0ZeTya8xXGj0hn+Wfvz7baJTVPtFcpL53c=,iv:ROu2YPg7f1oGSxP/Sg8SN1Jsc662VIVoMuPUHmS7E68=,tag:KL8r+dSse48KPr3pQ2EFdA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
