---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 29.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    logs:
      general:
        # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: ERROR
        # -- Set the format of General Logs to be either Common Log Format or JSON. For more information: https://doc.traefik.io/traefik/observability/logs/#format
        format: common
      access:
        enabled: true
    defaultCertificate: cluster-cert
    service:
      main:
        type: ClusterIP
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        externalTrafficPolicy: Local
        ports:
          web:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
          websecure:
            enabled: true
            port: 443
            protocol: https
            # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
            forwardedHeaders:
              enabled: false
              # -- List of trusted IP and CIDR references
              trustedIPs: []
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: false
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs: []
              # -- Trust every incoming connection
              insecureMode: false
    ingress:
      main:
        enabled: false
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - traefik.${BASE_DOMAIN}
            clusterIssuer: cluster-cert
        hosts:
          - host: traefik.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
